collections:
    robots:
        - name: 'ropod_001'
          smart_wheel_count: 4
        - name: 'ropod_002'
          smart_wheel_count: 4
        - name: 'ropod_003'
          smart_wheel_count: 4
    experiments:
        - id: 'linear_motion'
          name: 'Linear motion'
        - id: 'in_place_rotation'
          name: 'In-place rotation'
        - id: 'area_navigation'
          name: 'Area navigation'
        - id: 'path_planner_area_navigation'
          name: 'Area navigation using a path planner'
        - id: 'elevator_entering'
          name: 'Elevator entering'
        - id: 'elevator_exiting'
          name: 'Elevator exiting'
        - id: 'dock'
          name: 'Docking'
        - id: 'undock'
          name: 'Undocking'
        - id: 'nav_dock_undock'
          name: 'Navigation, docking, and undocking'
        - id: 'dock_and_enter_elevator'
          name: 'Docking and elevator entering'
        - id: 'elevator_navigation'
          name: 'Elevator navigation'
    queries:
        - id: 'get_all_ongoing_tasks'
          name: 'All ongoing tasks'
        - id: 'get_all_scheduled_tasks'
          name: 'All scheduled tasks'
        - id: 'get_robots_assigned_to_task'
          name: 'Robots assigned to task'
        - id: 'get_tasks_assigned_to_robot'
          name: 'Tasks assigned to robot'
    maps:
        - name: 'amk-basement'
          path: '/static/maps/amk/basement.png'
          display_scale: 0.15
          width: 3942
          height: 8659
          xrange: [-1250, 2500]
          yrange: [-7500, 2700]
          origin_x: -1250
          origin_y: 1250
          resolution: 0.02
        - name: 'brsu-c-floor0'
          path: '/static/maps/brsu/c-floor0.png'
          display_scale: 0.15
          width: 4598
          height: 4228
          xrange: [-1200, 3500]
          yrange: [-200, 4000]
          origin_x: -1250
          origin_y: 4000
          resolution: 0.02
